### ISSUE TITLE
gotype blocks other linters and doesn't work

### ISSUE THREAD

**Issue by abourget** [sirreal/SublimeLinter-contrib-gotype#8]
With a fresh install of GoSublime, following this guide: https://github.com/abourget/getting-started-with-golang/blob/master/Setting_up_Sublime_properly.md
it appears that `gotype` blocks linting from even `golint` and `govet`.

Not sure how to debug and get things working again.. so will be suggesting to disable `gotype`.

**Comment by rasky** [comment]
Try activate SublimeLinter debugging and then look at the console. There should be some information on what's going on. 

I can't see how a liner plugin can prevent others from running though.

**Comment by abourget** [comment]
It seems to prevent golint and govet linters from doing their job.. Other
contrib plugins

**Comment by rasky** [comment]
Can you please follow the instructions I gave you to help me debug the issue? I run all those plugins at the same time and I don't see the problem you see.

Try activating SublimeLinter debugging (`Tools -> SublimeLinter -> Debug Mode`), then open the console (`View -> Show Console`), open a file and trigger the linter (depending on how you configured SublimeLinter, you need to either run it manually, or save the file, or just open it). 

The console output should show what SublimeLinter is running and the output of those commands. If you have configured `golint`, `gotype` and `govet`, you should see those three plugins being launched, together with the command line they run.

Paste me the console output so that we can look into the problem.

**Comment by sirreal** [comment]
Closed due to lack of input.
